In this assignment, you will create several functions that perform various conversions of _positive_ numbers from binary to decimal and vice versa. 
You will do both fixed point and floating point. 

You will need to import numpy.  I suggest that you use: 

In [1]:
from numpy import *

You will be using bit arrays and numbers. A bit array is an array of 0's and 1's, such as:

In [2]:
bitArray1 = array([1,1,1,0,1])

In [3]:
bitArray1[0]

1

which represents the binary number 29 = 16+8+4+1.

Note:

- Exercise 6 below is mostly done for you. You may use this as inspiration for the others.
- You may make use of functions that have been defined earlier in later functions (for example, the code in Exercise 6 uses the functions `decInt2Bin` and `dec2BinFixed` that were defined in Exercises 2 and 4 , respectively. 


Exercise 1: Create a function called 'bin2decInt' that converts the first 'nBits' in an array of bits (0's and 1's) to a _positive_ decimal integer. The function 'bin2decInt' has two arguments: 

- bitArray = array of bits, 
- nBits= num. of bits to convert

Here is a step-by-step  example of how the algorithm:

_Example_: Convert [1,0,1,1,0] to decimal

- Take the top bit (1) as the first result
- Multiply the first result by 2 and add the next bit (0) to get the second result: 2*1 + 0 = 2.
- Multiply the second result by 2 and add the next bit (1) to get the third result: 2*2 + 1 = 5
- Multiply the third result by 2 and add the next bit (1) to get the fourth result: 2*5 + 1 = 11
- Multiply the fourth result by 2 and add the next bit (0) to get the fifth result: 2*11 + 0 = 22.

A steps by step description of the code is given in the comments in the cell below. Note that you do not need to add any more statements: just complete the ones that are there.

In [4]:
from numpy import *

# a. Define the function using the 'def' statement
def bin2decInt(bitArray, nBits):
    
# b. Initialize 'decVal' to zero.  decVal will contain the intermediate results, as well as the final result.
    decVal = 0

# c. Start a 'for' loop  Let k be your loop variable. k ranges from 0 to nBits,
#    in order to run through all of the bits in bitArray
    for k in range(nBits):
# d. Multiply the previous result (which is stored in decVal) by 2, and add the next bit
        result = 2 * decVal + bitArray[k]    
        decVal = result

# e. When the loop is finished, return the final value.    
    return result
    
# f. Test the code by converting 110101 = 32 + 16  + 4 + 1

a = array([1,1,0,1,0,1])
b = len(a)
print(bin2decInt(a,b))
#print(bin2decInt(array([1,0,1,1,0]), 5))

53


Exercise 2. Create a function 'decInt2bin' to convert a decimal integer to an array of nBits binary bits. 
The function 'decInt2bin' has two arguments:

- bdecVal = decimal value to convert to binary 
- nBits= num. of bits in result

An example of the algorithm for a specific case is as follows:

_Example_: Convert 21 to an array of 6 binary bits:

- The remainder of 21 when divided by 2 is 1, so 1 is the lowest bit
- Do an integer divide of 21 by 2 to obtain the truncated value 10.  This has the effect of removing the last bit, and shifting all other bits to the right so that the last bit of this truncated value is the second bit of the original number.
- The remainder of the truncated value (10) when divided by 2 is 0, so 0 is the second bit.
- Do an integer divide of 10 by 2 to obtain the new truncated value (5)
- The remainder of 5 when divided by 2 is 1, so 1 is the third bit.
- Do an integer divide of 5 by 2 to obtain the new truncated value (2)
- The remainder of 2 wend divided by 2 is 0, so 0 is the fourth bit.
- Do an integer divide of 2 by 2 to obtain the new truncated value (1)
- The remainder of 1 when divided by 2 is 1, so 1 is the fifth bit.
- Do an integer divide of 1 by 2 to obtain the next truncted value (0)
- The remainder of 0 when divided by 2 is 0, so 0 is the sixth bit.

See if you can design your code to generalize this procedure. A step-by-step code outline is given below.  Note that each lettered item corresponds to 1 code statement.

In [5]:
from numpy import *

# a. Define the function using the 'def' statement
def decInt2bin (bdecVal, nBits):
# b. Initialize an array called bitArray to contain the bits
#     It's convenient to initialize as an array of zeros of length nBits
    bitArray = zeros(nBits)

# c. During the process of computation, we will be taking our original
#    decimal value and changing it.  So we define another variable 'truncVal'to 
#    hold the changing value.  'truncVal' should be initialized to equal the 
#    decimal number to be converted
    trunVal = bdecVal
    
# d. Next, start a 'for' loop to generate the bits one by one (from lowest
#    to highest).  Let 'k' be your loop variable
# e. Make the k'th bit = 0 if 'truncVal' is even, and 1 if 'truncVal' is odd
# f. Shift truncVal so that all of the bits move to the right.
# g. The bits are now in the wrong order (lowest to highest).  We want the 
#    bits in highest to lowest order.  So we reverse the order when we return the bits.
# h. Test your code by converting 429 to a binary array of size 9, 
#    and back again (this will require two statements). Print both 
#    the binary array, and the reconverted result.
    for k in range(nBits):
        if trunVal % 2 == 0:
            bitArray[k] = 0
        elif trunVal % 2 == 1:
            bitArray[k] = 1
        else:
            return("Please select an integer!")
            
        
        trunVal = trunVal // 2
    return bitArray[::-1]

a = 429
b = 9

p = decInt2bin(a, b)
q= len(p)


print("Binary array is:", decInt2bin(a, b), "\n")

print("The equivalent decimalInteger is:", bin2decInt(p,q), "\n")




Binary array is: [1. 1. 0. 1. 0. 1. 1. 0. 1.] 

The equivalent decimalInteger is: 429.0 



In [6]:
decInt2bin(26, 6)

array([0., 1., 1., 0., 1., 0.])

Exercise  3. Create a function to convert a decimal value (`decVal`) to fixed point binary with `bitNums[0]` integer
and `bitNums[1]` fractional bits. Call the function `decFixed2bin`.  

The function takes two inputs: 

- `decVal` (decimal value)

- `bitNums` (2-element list that contains the number of integer and fractional bits.

The function returns as output an array of bits (0's and 1's) named `binArray`

In [7]:
from numpy import *

def dec2binFixed(decVal,bitNums):
    bitArray = array([])
    val = decVal
    
    Int = val // 1
    Frac = val - Int
    
    if Int >= 1:
        result1 = decInt2bin(Int, bitNums[0])
        bitArray = append(bitArray, result1)
        
    elif Int < 1:
        bitArray = append(bitArray, zeros(bitNums[0]))
        
    if Frac == 0:
        bitArray = append(bitArray, zeros(bitNums[1]))
        
    else:
        for k in range(bitNums[1]):
            result2 = (2 * Frac) // 1
            bitArray = append(bitArray, result2)
            if result2 == 0:
                Frac = 2 * Frac
            elif result2 == 1:
                Frac = (2*Frac) - 1
    return bitArray


print(dec2binFixed(20.1875, [5,4]))

[1. 0. 1. 0. 0. 0. 0. 1. 1.]


Exercise  4. Create a function named `bin2decFixed` that converts the  first `sum(bitNums)` bits in an array of bits 
to a positive decimal fixed point. `Here bitNums[0]` = no. integer bits and `bitNums[1]` = no. of fractional bits.
Function inputs are:
    
- `binArray`  (array of binary bits)
` `bitNums`  (list of two numbers, as described above)

The function returns a decimal fixed point value.  You may find it useful to take advantage of the `bin2decInt` function that you created above.

In [8]:
from numpy import *

def bin2decFixed(binArray, bitNums):
    ## aiming to get 1/2, 1/4, 1/8...
    a = array([])
    for k in range(1, bitNums[1] + 1):
        result1 = 2 ** (-k)
        a = append(a, result1)
        
    # aiming to find the range of values to multiply with above    
    b = binArray[bitNums[0] : sum(bitNums)]
    
    # c is the mantissa value
    c = sum(a*b)
    
    dec_Val = bin2decInt(binArray[range(bitNums[0])], bitNums[0]) + c
    
    return dec_Val
    
p = array([0,1,0,0,0,0,1,1])
q = [4, 4]
    
print(bin2decFixed(p,q))  



4.1875


Exercise 5. Test your decFixed2bin and bin2decFixed codes by converting fixed point decimal 337.45 
to a fixed point binary with 10 integer and 6 fractional bits, and convert
back again.  The final answer should nearly agree with 337.45 (why doesn't it
agree exactly?)

In [9]:
a = dec2binFixed(337.45, [10,6])

print("Fixed point binary:", a, "\n")

print("binary to Fixed point:", bin2decFixed(a, [10,6]), "\n")

b = dec2binFixed(337.45, [10,7])
print("a:", a, "\n")

print("In 'b', the number of fractional bits is increased: ie 1 is added to the end of 'a'.")
print("b:", b, "\n")
print("Equiv. binary to Fixed point for b:", bin2decFixed(b, [10,7]), "\n")

print("By increasing the number of fractional bits (mantissa) the precision increases. Therefore, the result isn't exactly 337.45 due to errors resulting from truncation.")






Fixed point binary: [0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0.] 

binary to Fixed point: 337.4375 

a: [0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0.] 

In 'b', the number of fractional bits is increased: ie 1 is added to the end of 'a'.
b: [0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 1.] 

Equiv. binary to Fixed point for b: 337.4453125 

By increasing the number of fractional bits (mantissa) the precision increases. Therefore, the result isn't exactly 337.45 due to errors resulting from truncation.


Exercise 6. Convert a decimal floating point to binary.  The function inputs are the
decimal number, and a list called `bitNums` of 2 numbers giving the number of exponential 
bits in the converted result and the number of mantissa bits. The exponent is in biased form: the bias 
is `2**(bitNums[0]-1)`.  In other words, when you convert the exponent to an integer, add the bias before converting it to binary. 

You may complete the code outline below.

In [13]:
from numpy import *

# Code for Exercise 6. There are 2 statements for you to complete.
def decFloat2bin(decVal,bitNums):
    nExpBits = bitNums[0]
    nMantBits = bitNums[1]
    expIntVal = int(floor(log2(decVal)))
    expIntBiased = expIntVal + 2**(bitNums[0]-1)
    expBitArray = decInt2bin(expIntBiased,nExpBits)
    mantDecVal = decVal/(2**expIntVal)-1
    mantBitArray= dec2binFixed(mantDecVal,[0,nMantBits])
    return expBitArray,mantBitArray
# The following statement tests the code
# Note the code will not work until you write the functions decInt2bin and dec2binFixed
print(decFloat2bin(.00123,[5,10]))

(array([0., 0., 1., 1., 0.]), array([0., 1., 0., 0., 0., 0., 1., 0., 0., 1.]))


Exercise 7.  Create a code that converts a binary exponent and binary mantissa into a floating point decimal

In [14]:
from numpy import *

# Code for Exercise 7
def bin2decFloat(expBitArray,mantBitArray):
    exp_biased = bin2decFixed(expBitArray, [len(expBitArray), 0])
    exp_int_val = exp_biased - 2**(len(expBitArray)-1)
    mant_w_leading1 = append(array([1]), mantBitArray)
    mant_val_plus1 = bin2decFixed(mant_w_leading1, [1, len(mantBitArray)])
    decVal = mant_val_plus1 * 2**exp_int_val
    
    return decVal

8. Test your `decFloat2bin` and `bin2decFloat` codes by converting 17.9E12 to
binary with 7 exponent bits and 9 mantissa bits, and back again.

In [23]:
# Put your code for #8 here.

a = print(decFloat2bin(17.9 * (10**12),[7,9]))

a_exp_array = array([1,1,0,1,1,0,0])
a_mant_array = array([0,0,0,0,0,1,0,0,0])


print(bin2decFloat(b, c))


(array([1., 1., 0., 1., 1., 0., 0.]), array([0., 0., 0., 0., 0., 1., 0., 0., 0.]))
17867063951360.0
